### ISSUE TITLE
Redirect bug after sign up

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/drops#232]
On sign up Drops redirects me to a page rendering the view attached. Any suggestions what happens?
![screenshot from 2018-06-15 15-04-27](https://user-images.githubusercontent.com/5207572/41469481-b0f084fe-70ad-11e8-9dc7-fdcd65008865.png)

**Comment by johannsell** [comment]
My stack trace:
```
cat: /VERSION: No such file or directory
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/docker/lib/ch.qos.logback.logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/docker/lib/org.slf4j.slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] - application - ReactiveMongoApi starting...
[info] - application - ReactiveMongoApi successfully started with DB 'drops'! Servers:
		[mongo:27017]
[info] - play.api.Play - Application started (Prod)
[info] - play.core.server.NettyServer - Listening for HTTP on /0.0.0.0:9000
[info] - application - Checked index, result is Failure(reactivemongo.api.commands.DefaultWriteResult: DatabaseException['<none>'])
[debug] - application - http://172.2.100.4:9000/dispenser/template/full
[debug] - application - http://172.2.100.4:9000/dispenser/template/full
[debug] - application - http://172.2.100.4:9000/dispenser/template/full
[error] - play.core.server.netty.PlayDefaultUpstreamHandler - Cannot invoke the action
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.None$.get(Option.scala:345) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at daos.MariadbUserDao$$anonfun$daos$MariadbUserDao$$addProfiles$2.apply(UserDao.scala:283) ~[drops.drops-0.26.24-sans-externalized.jar:na]
	at daos.MariadbUserDao$$anonfun$daos$MariadbUserDao$$addProfiles$2.apply(UserDao.scala:283) ~[drops.drops-0.26.24-sans-externalized.jar:na]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Try$.apply(Try.scala:192) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Success.map(Try.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.8.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.11.8.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.8.jar:na]

```

**Comment by deinelieblings** [comment]
find(userDB.id).map(_.get) here _ can be None. A getOrElse can fix the bug.

**Comment by johannsell** [comment]
If we add a `Profile` to a `User` (has to be already in the database) and after insertion of the `Profile` the `User` can not be found inside the database, there is something terrible wrong with the insertion, I guess. :)

Let us discuss and debug on our next weekly.

**Comment by johannsell** [comment]
won't fix, since Drops Views and MongoDB are deprecated.
