### ISSUE TITLE
Bug: PasswordInfoDao

### ISSUE THREAD

**Issue by deinelieblings** [Viva-con-Agua/drops#339]
Error:  
```
[error] - play.core.server.netty.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.UnsupportedOperationException: empty.head
    at scala.collection.immutable.Vector.head(Vector.scala:193) ~[org.scala-lang.scala-library-2.11.8.jar:na]
    at daos.MariadbPasswordInfoDao$$anonfun$find$4.apply(PasswordInfoDao.scala:84) ~[drops.drops-0.36.54-sans-externalized.jar:na]
    at daos.MariadbPasswordInfoDao$$anonfun$find$4.apply(PasswordInfoDao.scala:84) ~[drops.drops-0.36.54-sans-externalized.jar:na]
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.util.Try$.apply(Try.scala:192) ~[org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.util.Success.map(Try.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.8.jar:na]
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.11.8.jar:na]
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.8.jar:na]  
```

Function: 
``` 
def find(id: Long) : Future[PasswordInfo] = {
    dbConfig.db.run(passwordInfos.filter(_.id === id).result).map(pInfo => PasswordInfo(pInfo.head.hasher, pInfo.head.password))
}
```
Programmatically, we access an empty `pInfo`, which throws the error. Using `headOption` should solve the problem. So we have to return a `Future[Option [PasswordInfo]]`. 

From the point of view of the workflow of `Drops`, a `None` means an error in the database.` PasswordInfoDB` is only called if the user is confirmed, for which a password must be stored.
To completely solve the problem, we should store an identifier of the affected users.

**Comment by deinelieblings** [comment]
New function:
```
  def find(id: Long) : Future[Option[PasswordInfo]] = {
    dbConfig.db.run(passwordInfos.filter(_.id === id).result).map(pInfoOption => pInfoOption.headOption match {
      case Some(pInfo) => Some(PasswordInfo(pInfo.hasher, pInfo.password))
      case _ => None
    })
  }
```
This function is only called when adding a model to the database. It therefore makes sense to catch the sql errors at this point. I assume that `PasswordInfo` is sometimes not stored in the database.
